//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPhoneNumber
    {
        public int StudentID { get; set; }
        public string phoneNumber { get; set; }
        public string homeNumber { get; set; }
        public string phonenumber2 { get; set; }
    
        public virtual StudentName StudentName { get; set; }
    }
}
