//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string address { get; set; }
        public string EmailAddress { get; set; }
        public string workInformation { get; set; }
        public string churchName { get; set; }
    
        public virtual StudentName StudentName { get; set; }
    }
}
